apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  namespace: n8n
  labels:
    type: local
spec:
  storageClassName: local-storage # creaet own storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"