environments:
  default:
    values:
      - namespace: n8n
      - domain: "n8n.app.local"
      - encryption_key: "iam not a secret"
      - db_password: "iam not a secret"

helmDefaults:
  wait: true
  timeout: 66

releases:
  - name: n8n
    namespace: {{ .Values.namespace }}
    chart: .
    values:
      - n8n:
          encryption_key: {{ .Values.encryption_key }}
      - config:
          host: {{ .Values.domain }}
      - persistence:
          enabled: true
          type: dynamic


