apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-n8n
  namespace: n8n
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: mysql-n8n
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-n8n
  namespace: n8n
spec:
  selector:
    matchLabels:
      app: mysql-n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-n8n
    spec:
      containers:
      - image: mysql:5.7.9
        name: mysql-n8n
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql-n8n
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-n8n
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-n8n
  namespace: n8n
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-n8n
  namespace: n8n
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


