apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selectors:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: webserver-nginx
        image: nginx
        resources:
          limits:
            memory: "10Mi"
            cpu: "100m"