apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
  namespace: wp
  labels:
    app.kubernetes.io/name: mariadb
    type: local
spec:
  storageClassName: local-storage # creaet own storage-class
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/mariadb"